# Generated by Django 5.2.9 on 2026-01-02 10:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('first_published', models.DateField()),
                ('pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Pages')),
                ('synopsis', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ManyToManyField(to='book.author')),
                ('genres', models.ManyToManyField(to='book.genre')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='book.language')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
