# Generated by Django 5.2.9 on 2026-01-09 21:10

from django.db import migrations, models
import django.core.validators
import book.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_front_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.PositiveIntegerField(
                default=2026, null=True, blank=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    book.models.max_value_current_year
                ]
            ),
        ),
    ]
