# Generated by Django 5.2.9 on 2026-01-09 21:20

import book.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_add_published_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.PositiveIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(1000), book.models.max_value_current_year]),
        ),
    ]
