# Generated by Django 5.2.9 on 2026-01-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurefeatures',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Currently Working On'), (2, 'Next in line'), (3, 'Pre-Planning Stage'), (4, 'Not on radar')], default=4),
        ),
    ]
