# Generated by Django 5.2.9 on 2026-01-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
