# Generated by Django 5.2.9 on 2026-01-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_status_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[(1, 'On Wishlist'), (2, 'Currently Reading'), (3, 'Read'), (4, 'Did Not Finished')]),
        ),
    ]
