# Generated by Django 5.2.9 on 2026-01-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'On Wishlist'), (2, 'Currently Reading'), (3, 'Read'), (4, 'Did Not Finish')]),
        ),
    ]
